### ISSUE TITLE
Script to check DL3 fits file validity

### ISSUE THREAD

**Issue by TarekHC** [open-gamma-ray-astro/gamma-astro-data-formats#117] opened 2018-07-24 08:08 UTC
Apart from a good example DL3 file (that will come soon with the HESS + joint-Crab data release, it would be nice to have a simple python script that checks if the HDUs contain the required header keywords.

Anyone is welcome to do this!

**Comment by cdeil** [comment] 2018-07-24 10:22
Agreed it would be very nice to have a lint tool for DL3 or any of the formats described here.

As I mentioned e.g. in https://github.com/open-gamma-ray-astro/gamma-astro-data-formats/pull/36#issuecomment-406786259 , I think it would be better to put this in Gammapy than here in the spec repo. At least I can say that if anyone would be willing to work on this, it would be very welcome in Gammapy (https://github.com/gammapy/gammapy/issues/1321).

In Gammapy there's already some things that we have to clean up in the next months anyways, e.g.
https://github.com/gammapy/gammapy/blob/622f24324c70d3b7514d58e12ca6601599d3293b/gammapy/data/event_list.py#L929

It's pretty common to have linters not published / maintained with the spec, but as part of software projects that work with that data.
E.g. for FITS there's the FITS standard, and then there's https://heasarc.gsfc.nasa.gov/ftools/caldb/help/ftverify.html
For VOTable there's the standard, and then there's
http://docs.astropy.org/en/stable/api/astropy.io.votable.validate.html

This spec repo already has very low contribution levels, and it might die for the DL3 part soon if the effort continues within CTA, as a rewrite or fork. So adding things here, I'm just worried that no-one will extend and maintain it as the formats evolve.

That said: if someone makes a PR here with a script, and no-one has time to put in the effort to polish it some more and put it in Gammapy, I think we should of course merge it. Something is better than nothing.

**Comment by MaxNoe** [comment] 2018-07-26 08:02
So it seems this is a duplicate of #42

**Comment by cdeil** [comment] 2018-07-26 08:45
Yes, closing this one.

**Closed by cdeil** 2018-07-26 08:45 UTC
Labels: status: discussion
